baseURL: "https://jeetdesai25.github.io/"
languageCode: "en-us"
title: "Jeet Desai"
theme: "PaperMod"

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    # - identifier: blog
    #   name: Blog
    #   url: /blog
    #   weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false
  social: true

  #

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Jeet Desai"
    subtitle: "👋 Hi, I'm Jeet - a Software Engineer and MS Computer Science student at Loyola Marymount University. I specialize in full-stack development with experience in building scalable web applications and machine learning solutions. I'm passionate about creating efficient tech solutions that make a real impact."
    imageUrl: "home/IMG_6664-modified.png"
    imageWidth: 250
    imageHeight: 250
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  #ERROR deprecated: .Site.Social was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.142.0. Implement taxonomy 'social' or use .Site.Params.Social instead.
  Social:
    email: "jeetdesai25@gmail.com"
    linkedin: "jeet-desai-"
    github: "JEETDESAI25"
    cv: "https://drive.google.com/file/d/15opQg7Qm5EbHanEdcP8pR-DY-i3qQ0pq/view?usp=sharing"

  socialIcons:
    - name: "email"
      url: "mailto:jeetdesai25@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/jeet-desai-/"
    - name: "github"
      url: "https://github.com/JEETDESAI25"
    - name: "cv"
      url: "https://drive.google.com/file/d/15opQg7Qm5EbHanEdcP8pR-DY-i3qQ0pq/view?usp=sharing"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
